/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#6e5b4d",
        "on-primary": "#fff6f2",
        background: "#fbf9f6",
        "on-background": "#30332f",
        surface: "#fbf9f6",
        "on-surface": "#30332f",
        "surface-variant": "#e2e3dd",
        "on-surface-variant": "#5d605b",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#eeeeea",
        "surface-container-high": "#e8e8e3",
        "surface-dim": "#d9dbd4",
        "color-on-secondary-fixed": "#4b3d31",
        "color-on-surface-variant": "#5d605b",
        "color-tertiary-fixed-dim": "#f0dcc9",
        "color-surface-bright": "#fbf9f6",
        "color-inverse-on-surface": "#9e9d9a",
        "color-error-dim": "#5c1202",
        "color-surface-container-lowest": "#ffffff",
        "color-primary-fixed": "#f8decc",
        "color-outline": "#797b77",
        "color-on-tertiary-fixed-variant": "#6e6051",
        "color-inverse-primary": "#fbe0cf",
        "color-on-secondary-container": "#5e4f42",
        "color-on-tertiary-container": "#645647",
        "color-on-primary-container": "#604e41",
        "color-inverse-surface": "#0e0e0d",
        "color-secondary-fixed-dim": "#e6d0c0",
        "color-error-container": "#fe8b70",
        "color-outline-variant": "#b1b3ad",
        "color-secondary": "#6c5c4f",
        "color-primary-dim": "#614f42",
        "color-on-tertiary-fixed": "#514436",
        "color-secondary-dim": "#605044",
        "color-on-tertiary": "#fff7f3",
        "color-on-surface": "#30332f",
        "color-background": "#fbf9f6",
        "color-on-secondary-fixed-variant": "#69584c",
        "color-secondary-container": "#f5dece",
        "color-error": "#9e422c",
        "color-primary": "#6e5b4d",
        "color-on-primary-fixed": "#4d3c30",
        "color-tertiary-container": "#ffebd7",
        "color-surface-tint": "#6e5b4d",
        "color-on-error": "#fff7f6",
        "color-tertiary": "#6b5d4e",
        "color-surface-container-high": "#e8e8e3",
        "color-surface-dim": "#d9dbd4",
        "color-surface-container-low": "#f5f3f0",
        "color-secondary-fixed": "#f5dece",
        "color-primary-container": "#f8decc",
        "color-surface-container-highest": "#e2e3dd",
        "color-surface-variant": "#e2e3dd",
        "color-on-error-container": "#742410",
        "color-surface": "#fbf9f6",
        "color-on-secondary": "#fff7f4",
        "color-surface-container": "#eeeeea",
        "color-tertiary-dim": "#5e5142",
        "color-on-background": "#30332f",
        "color-primary-fixed-dim": "#e9d0be",
        "color-on-primary-fixed-variant": "#6b584a",
        "color-tertiary-fixed": "#ffebd7",
        "color-on-primary": "#fff6f2",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
